// <auto-generated />
using System;
using System.Collections.Generic;
using BusBooking.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusBooking.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id")
                        .HasName("PK_Bookings");

                    b.HasIndex("BusId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.BookingPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_BookingPassengers");

                    b.HasIndex("SeatId");

                    b.HasIndex("BookingId", "SeatId")
                        .IsUnique()
                        .HasDatabaseName("UQ_BookingPassengers_Booking_Seat");

                    b.ToTable("BookingPassengers", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.BookingSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Fare")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_BookingSeats");

                    b.HasIndex("SeatId");

                    b.HasIndex("BookingId", "SeatId")
                        .IsUnique()
                        .HasDatabaseName("UQ_BookingSeats_Booking_Seat");

                    b.ToTable("BookingSeats", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<int>>("AvailableDays")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("BoardingPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<string>("DropPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMarkedForRemoval")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemporarilyDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MaintenanceEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MaintenanceStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("RetirementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Buses");

                    b.HasIndex("OperatorId");

                    b.HasIndex("RouteId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Buses", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_EmailLogs");

                    b.ToTable("EmailLogs", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Locations");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Locations_Name");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.OperatorOffice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_OperatorOffices");

                    b.HasIndex("OperatorId", "CityName")
                        .IsUnique()
                        .HasDatabaseName("UQ_OperatorOffices_Operator_City");

                    b.ToTable("OperatorOffices", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.OperatorProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("PK_OperatorProfiles");

                    b.ToTable("OperatorProfiles", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CardLast4")
                        .HasColumnType("text");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Payments");

                    b.HasIndex("BookingId");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Payments_TransactionId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.PlatformFeeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id")
                        .HasName("PK_PlatformFeeConfigs");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PlatformFeeConfigs_IsActive");

                    b.ToTable("PlatformFeeConfigs", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RefundPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("RefundStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Refunds");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Refunds_BookingId");

                    b.ToTable("Refunds", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Routes");

                    b.HasIndex("DestinationId");

                    b.HasIndex("SourceId", "DestinationId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Routes_Source_Destination");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatType")
                        .HasColumnType("text");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Seats");

                    b.HasIndex("VehicleId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Seats_Vehicle_Number");

                    b.ToTable("Seats", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Tickets");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tickets_BookingId");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tickets_Number");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeatLayoutType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Vehicles");

                    b.HasIndex("OperatorId");

                    b.HasIndex("VehicleNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Vehicles_Number");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.Bus", "Bus")
                        .WithMany("Bookings")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Buses_BusId");

                    b.HasOne("BusBooking.Api.Domain.Entities.User", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Users_PassengerId");

                    b.Navigation("Bus");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.BookingPassenger", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingPassengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingPassengers_Bookings_BookingId");

                    b.HasOne("BusBooking.Api.Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.BookingSeat", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingSeats_Bookings_BookingId");

                    b.HasOne("BusBooking.Api.Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BookingSeats_Seats_SeatId");

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Bus", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Buses_Users_OperatorId");

                    b.HasOne("BusBooking.Api.Domain.Entities.Route", "Route")
                        .WithMany("Buses")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Buses_Routes_RouteId");

                    b.HasOne("BusBooking.Api.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Buses")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Buses_Vehicles_VehicleId");

                    b.Navigation("Operator");

                    b.Navigation("Route");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.OperatorOffice", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.User", "Operator")
                        .WithMany("OperatorOffices")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OperatorOffices_Users_OperatorId");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.OperatorProfile", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.User", "User")
                        .WithMany("OperatorProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OperatorProfiles_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Payment", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Bookings_BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Refund", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.Booking", "Booking")
                        .WithMany("Refunds")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Refunds_Bookings_BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Route", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.Location", "Destination")
                        .WithMany("DestinationRoutes")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Routes_Locations_DestinationId");

                    b.HasOne("BusBooking.Api.Domain.Entities.Location", "Source")
                        .WithMany("SourceRoutes")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Routes_Locations_SourceId");

                    b.Navigation("Destination");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Seat", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Seats")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Seats_Vehicles_VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Bookings_BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles_RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("BusBooking.Api.Domain.Entities.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_Users_OperatorId");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingPassengers");

                    b.Navigation("BookingSeats");

                    b.Navigation("Payments");

                    b.Navigation("Refunds");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Bus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Location", b =>
                {
                    b.Navigation("DestinationRoutes");

                    b.Navigation("SourceRoutes");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Route", b =>
                {
                    b.Navigation("Buses");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("OperatorOffices");

                    b.Navigation("OperatorProfiles");
                });

            modelBuilder.Entity("BusBooking.Api.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Buses");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
