-- This schema is generated by EF Core migrations in runtime.
-- It is included here for visibility and DBA review.

create table roles (
  id uuid primary key,
  name varchar(30) not null unique
);

create table users (
  id uuid primary key,
  username varchar(100) not null unique,
  email varchar(200) not null unique,
  password_hash text not null,
  role_id uuid not null references roles(id),
  is_active boolean not null default true,
  created_at timestamp not null
);

create table operator_profiles (
  id uuid primary key,
  user_id uuid not null unique references users(id),
  vehicle_number varchar(100) not null,
  approval_status varchar(30) not null,
  is_enabled boolean not null,
  approved_by uuid null,
  approved_at timestamp null,
  rejection_reason text null
);

create table source_locations (
  id uuid primary key,
  name varchar(100) not null unique,
  is_active boolean not null default true
);

create table destination_locations (
  id uuid primary key,
  name varchar(100) not null unique,
  is_active boolean not null default true
);

create table routes (
  id uuid primary key,
  source_id uuid not null references source_locations(id),
  destination_id uuid not null references destination_locations(id),
  is_active boolean not null default true,
  unique(source_id, destination_id)
);

create table buses (
  id uuid primary key,
  operator_id uuid not null references users(id),
  route_id uuid not null references routes(id),
  bus_name varchar(150) not null,
  boarding_point varchar(150) not null,
  drop_point varchar(150) not null,
  departure_time timestamp not null,
  duration_minutes integer not null,
  base_price numeric(10,2) not null,
  platform_fee numeric(10,2) not null,
  total_price numeric(10,2) not null,
  seat_layout_type varchar(40) not null,
  total_seats integer not null,
  approval_status varchar(30) not null,
  is_active boolean not null default true,
  is_temporarily_disabled boolean not null default false,
  created_at timestamp not null
);

create table seats (
  id uuid primary key,
  bus_id uuid not null references buses(id),
  seat_number varchar(20) not null,
  seat_type varchar(30) null,
  is_active boolean not null default true,
  unique(bus_id, seat_number)
);

create table bookings (
  id uuid primary key,
  passenger_id uuid not null references users(id),
  bus_id uuid not null references buses(id),
  booking_status varchar(30) not null,
  total_amount numeric(10,2) not null,
  booked_at timestamp not null,
  cancelled_at timestamp null,
  cancellation_reason text null
);

create table booking_seats (
  id uuid primary key,
  booking_id uuid not null references bookings(id),
  seat_id uuid not null references seats(id),
  fare numeric(10,2) not null,
  unique(booking_id, seat_id)
);

create table payments (
  id uuid primary key,
  booking_id uuid not null references bookings(id),
  transaction_id uuid not null unique,
  payment_status varchar(20) not null,
  amount numeric(10,2) not null,
  gateway varchar(50) not null,
  card_last4 varchar(4) null,
  attempted_at timestamp not null,
  response_payload text null
);

create table email_logs (
  id uuid primary key,
  user_id uuid null references users(id),
  to_email varchar(200) not null,
  subject varchar(200) not null,
  template_key varchar(100) not null,
  status varchar(20) not null,
  error_message text null,
  created_at timestamp not null
);
